# Site settings
title: shehab ashraf
email: 
description:
baseurl: ""
url: "http://shehabashraf.github.io"
twitter_username: _Sashraf
github_username:  shehab-ashraf

# Build settings
markdown: kramdown 
highlighter: rouge
permalink: /posts/:title/
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
